### ISSUE TITLE
객체인식

### ISSUE THREAD

**Issue by inwonse** [2021-SMHRD-KDT-AI-7/Object-Detection#1]

**Comment by kimjungsik** [comment]
- [ ] 데이터 폴더 or zip 자동 업로드 기능 구현
- [ ] 데이터 전처리 함수 구현
- [ ] 학습 데이터 NPZ 작업 , 데이터셋 수치화 작업.
- [ ] NPZ 로딩 (전처리 완료와 학습된 데이터셋 불러오는 것.)
- [ ] CNN 모델링(프로토타입_객체인식_수준)
- [ ] CNN 모델 개선을 위한 논문 분석으로 레이어 층 구현
    ㄴ 분석 및 현재 나와있는 기술 논문 분석
- [ ] CNN 모델 최적화 진행.
- [ ] 최적화된 모델 작업( 모델 체크 포인트 기능과 모델 학습 조기중단 기능 )
- [ ] 이미지 셋 넣어서 테스트 확인. (갯수 기능)
- [ ] ㄴ 다중 객체 인식...필요..
      ㄴ 리스트셋 준비해서 같은 물품 별 카운트 갯수 반환.          -> 나의 최종 목표.
          이미지 내에서도 객체별로 탐지해서 리스트에 담기
           인식한 영역 시작점과 끝점 찾아서 따로 파일형태로 만들기.

**Comment by inwonse** [comment]
데이터 폴더 or zip 자동 업로드 기능 구현
데이터 전처리 함수 구현
학습 데이터 NPZ 작업 , 데이터셋 수치화 작업.
NPZ 로딩 (전처리 완료와 학습된 데이터셋 불러오는 것.)
CNN 모델링(프로토타입_객체인식_수준)
CNN 모델 개선을 위한 논문 분석으로 레이어 층 구현
ㄴ 분석 및 현재 나와있는 기술 논문 분석
CNN 모델 최적화 진행.
최적화된 모델 작업( 모델 체크 포인트 기능과 모델 학습 조기중단 기능 )
이미지 셋 넣어서 테스트 확인. (갯수 기능)

다중 객체 인식...필요 구상안함 ( 앞선 모델에 따라 구조 설계해야하기 때문에)
검증데이터 준비해서 같은 물품 별 카운트 갯수 반환. -> 나의 최종 목표.
이미지 내에서도 객체별로 탐지해서 리스트에 담기 ( 다중 객체 인식 )
